language: java
jdk:
  -openjdk8

addons:
  sonarcloud:
    organization: "giulsdesideri30"
    token: 
      secure: 746d6080d52ef97f4b52e6ad97b67b6f13fb1119 

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ant build
  - sonar-scanner
